<br />
<div id="welcome">

    <h1>Bienvenido a Frutisoft</h1>
    <br /><br />
    <div style="float:left;width:50%;text-align: center">
        <img id="logo" src="../imgs/logoFruisoft.png" />
    </div>
    <div class="modulos">
        <ul class="modulos">
            <li>Módulos del sistema</li>
            <li><a href="">Administración</a></li>
            <li><a href="">Cosecha</a></li>
            <li><a href="">Pedidos</a></li>
            <li><a href="">Planeación</a></li>
            <li><a href="">Seguimiento</a></li>
        </ul>

    </div>
</div>